# Jekyll Resume Theme

# Site settings
title: Rohan Bhargava
email: r2bharga at ucsd.edu
description: 
baseurl: ""
url: "http://rohan-b.github.io/"
name: Rohan Bhargava
job: computer science student 
location: Bay Area, CA
languages: Java, C, Javascript
twitter_username: rohanb
github_username:  Rohan-B
codepen_username:  
email_address: r2bharga@ucsd.edu

# Build settings
markdown: kramdown
